package com.alganiug.systems.loanManagement.models.constants;

public enum LoanStatus {
    DRAFT, SUBMITTED, KYC_PENDING, KYC_APPROVED, HR_REVIEW, HR_APPROVED, MANAGER_REVIEW, APPROVED, DISBURSED, ACTIVE,
    COMPLETED, CHANGES_REQUESTED, REJECTED, LATE, DEFAULTED, CANCELLED
}
